---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak-system
spec:
  db:
    vendor: postgres
    host: postgres-internal-svc
    usernameSecret:
      name: postgres-db-creds
      key: admin-user
    passwordSecret:
      name: postgres-db-creds
      key: admin-password
