apiVersion: v1
kind: ConfigMap
metadata:
  name: luna-config
data:
  Chrystoki.conf: |-
    Chrystoki2 = {
       LibUNIX = /opt/safenet/lunaclient/lib/libCryptoki2.so;
       LibUNIX64 = /opt/safenet/lunaclient/lib/libCryptoki2_64.so;
    }

    Luna = {
      DefaultTimeOut = 500000;
      PEDTimeout1 = 100000;
       PEDTimeout2 = 200000;
      PEDTimeout3 = 20000;
      KeypairGenTimeOut = 2700000;
      CloningCommandTimeOut = 300000;
      CommandTimeOutPedSet = 720000;
    }

    CardReader = {
      RemoteCommand = 1;
    }

    Misc = {
      PE1746Enabled = 0;
       ToolsDir = /opt/safenet/lunaclient/bin;
       ProtectedAuthenticationPathFlagStatus = 0;
    }
    LunaSA Client = {
       ReceiveTimeout = 20000;
       SSLConfigFile = /opt/safenet/lunaclient/bin/openssl.cnf;
       ClientPrivKeyFile = /opt/safenet/lunaclient/cert/client/testserverKey.pem;
       ClientCertFile = /opt/safenet/lunaclient/cert/client/testserver.pem;
       ServerCAFile = /opt/safenet/lunaclient/cert/server/CAFile.pem;
       NetClient = 1;
       TCPKeepAlive = 1;
    }
