apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: luna-client-is
spec:
  lookupPolicy:
    local: false
  tags:
  - name: "ubi8"
    from:
      kind: DockerImage
      name: registry.redhat.io/ubi8
    referencePolicy:
      type: Source