apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-luna
  labels:
    app: nginx-luna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-luna
  template:
    metadata:
        labels:
          app: nginx-luna
    spec:
      serviceAccountName: default
      containers:
      - name: nginx
        image: bitnami/nginx
        volumeMounts:
        - name: assets
          mountPath: /app
      - name: luna-client
        image: luna-client:latest
        command: ["sh","-c","while true; do cat /tmp/Chrystoki.conf; sleep 30; done"]
        volumeMounts:
        - name: luna-config
          mountPath: /tmp/Chrystoki.conf
          subPath: Chrystoki.conf
        env:
        - name: ChrystokiConfigurationPath
          value: "/tmp/Chrystoki.conf"
      volumes:
        - name: assets
          persistentVolumeClaim:
          claimName: nginx-assets-pvc
        - name: luna-config
          configMap:
            name: luna-config
