apiVersion: apps/v1
kind: Deployment
metadata:
  name: luna-client
  labels:
    app: luna-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luna-client
  template:
    metadata:
        labels:
          app: luna-client
    spec:
      serviceAccountName: default
      containers:
      - name: luna-client
        image: luna-client:latest
        command:
            - sh
            - '-c'
            - while true; do cat /tmp/Chrystoki.conf; sleep 30; done
        volumeMounts:
        - name: luna-config
          mountPath: /tmp/Chrystoki.conf
          subPath: Chrystoki.conf
        env:
        - name: ChrystokiConfigurationPath
          value: "/tmp/Chrystoki.conf"
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/Chrystoki.conf
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
        - name: luna-config
          configMap:
            name: luna-config
