apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: patch-subscription.yaml
  target:
    group: operators.coreos.com
    kind: Subscription
    name: rhbk-operator
    version: v1alpha1
- path: patch-operatorgroup.yaml
  target:
    group: operators.coreos.com
    kind: OperatorGroup
    name: keycloak-og
    version: v1
- path: patch-namespace.yaml
  target:
    kind: Namespace
    name: patch_here
    version: v1
