apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres-base

generatorOptions:
  disableNameSuffixHash: true
  labels:
    component: postgres

resources:
  - postgres-namespace.yaml
  - postgres-pvc.yaml
  - postgres-internal-service.yaml
  - postgres-statefulset.yaml

secretGenerator:
- name: postgres-db-creds
  literals:
  - admin-user=postgres
  - admin-password=secretpassword