apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres-internal-service
  selector:
    matchLabels:
      component: postgres
  replicas: 1
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
              protocol: TCP
              port: 5432
          volumeMounts:
            - mountPath: /data
              name: data-volume
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: admin-user
                  name: postgres-db-creds
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: admin-password
                  name: postgres-db-creds
            - name: PGDATA
              value: /data/pgdata
            - name: POSTGRES_DB
              value: keycloak
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: postgres-data-pvc
