apiVersion: v1
kind: Service
metadata:
  name: postgres-internal-svc
  labels:
    component: postgres
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    component: postgres